### ISSUE TITLE
安卓的吗，还是什么的

### ISSUE THREAD

**Issue by su350380433** [hanfeihang/zhuoyao#1]

**Comment by hanfeihang** [comment]
目前只支持iOS，如果需要支持安卓的功能，欢迎PR

**Comment by zhanghailu** [comment]
写入: <?xml version="1.0"?><gpx version="1.1" creator="gpxgenerator.com"><wpt lat="31.17653618336825" lon="121.40480562066158"></wpt></gpx>
Error: Command failed: osascript /Users/zhanghailu/Documents/Personal/tec/dingwei/zhuoyao/apple_script/xcode_simulation
/Users/zhanghailu/Documents/Personal/tec/dingwei/zhuoyao/apple_script/xcode_simulation: execution error: 变量“xcode_simulation”没有定义。 (-2753)

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'osascript ' +
    '/Users/zhanghailu/Documents/Personal/tec/dingwei/zhuoyao/apple_script/xcode_simulation'
}

**Comment by zhanghailu** [comment]
编译执行`osacompile -e xcode_simulation -o xcode_simulation`
