### ISSUE TITLE
目前用的很不错，就是接口总是崩

### ISSUE THREAD

**Issue by yujian0815** [hanfeihang/zhuoyao#11]

**Comment by yujian0815** [comment]
写入: <?xml version="1.0"?><gpx version="1.1" creator="gpxgenerator.com"><wpt lat="29.890112923094836" lon="114.32589644041163"></wpt></gpx>
{ Error: Command failed: osascript /Users/jan/Downloads/zhuoyao/apple_script/xcode_simulation
/Users/jan/Downloads/zhuoyao/apple_script/xcode_simulation: execution error: “System Events”遇到一个错误：不能获得“menu item "Location" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode"”。 (-1728)
有时会被错，必须要手动点下location才生效

**Comment by hanfeihang** [comment]
偶尔我也会出这个现象，偶尔！重启下xcode试试看吧。
