### ISSUE TITLE
求教，小白一个，自行摸索了两天

### ISSUE THREAD

**Issue by Whi8per** [hanfeihang/zhuoyao#15]
<img width="566" alt="屏幕快照 2019-05-21 22 26 51" src="https://user-images.githubusercontent.com/20651237/58104858-154df280-7c18-11e9-86d8-736408b65ce0.png">
一窍不通的小白，从下xcode到配置node，几天也没完全明白，现在的问题是点飞行，右上角显示成功，但是实际没变化，终端显示如上图，求大佬指导一下

**Comment by Whi8per** [comment]
解决啦，头都大了，难为我这个摄影专业的了，QAQ，多谢大佬

**Comment by CMMJ** [comment]
求教程

**Comment by CMMJ** [comment]
> 解决啦，头都大了，难为我这个摄影专业的了，QAQ，多谢大佬

可以加你微信吗？教教我这个ios小白
