### ISSUE TITLE
大神关于飞行报错

### ISSUE THREAD

**Issue by CMMJ** [hanfeihang/zhuoyao#18]

**Comment by CMMJ** [comment]
![image](https://user-images.githubusercontent.com/35121936/58270594-c3929d00-7dbc-11e9-96e3-d05705af009f.png)

**Comment by CMMJ** [comment]
问题一，这个脚本是怎么编译的？我在脚本编辑器中好像编辑报错
![image](https://user-images.githubusercontent.com/35121936/58270719-0f454680-7dbd-11e9-8b19-a4b20f90120b.png)

**Comment by CMMJ** [comment]
问题二，如果前面的问题都解决了，是不是启动服务后，在自己的手机端打开网页点飞行就可以的了？
![IMG_4027的副本](https://user-images.githubusercontent.com/35121936/58271010-a7dbc680-7dbd-11e9-85bc-f8a61c98db89.PNG)

**Comment by CMMJ** [comment]
java码农一名，第一次接触xcode，不是很懂xcode，使用大神这个代码，需要在xcode启动吗？我是在vscode里面跑的，望大神指点迷津啊！！！盼回

**Comment by CMMJ** [comment]
问题一解决了，又来了一个新问题，是要在真机上调试才可以修改真机的定位吗？

**Comment by yang464352187** [comment]
请问问题一是怎么解决的，我现在能实时改变gpx的定位，但是好像Applescript并不能成功

**Comment by yang464352187** [comment]
> 问题一解决了，又来了一个新问题，是要在真机上调试才可以修改真机的定位吗？

请问问题一是怎么解决的，我现在能实时改变gpx的定位，但是好像Applescript并不能成功

**Comment by CMMJ** [comment]
> 请问问题一是怎么解决的，我现在能实时改变gpx的定位，但是好像Applescript并不能成功

要打开xcode的调试功能才行

**Comment by CMMJ** [comment]
摸索了两天，问题已经解决了
