### ISSUE TITLE
wss问题请教，详情在里面

### ISSUE THREAD

**Issue by RedShameA** [hanfeihang/zhuoyao#19]
我抓包显示每个socket包前面都有一个字母，但是我看遍了能看懂的代码也没看出来是怎么生成的，求作者能指点迷津。
如下开头的'E'
E{"request_type":"1004","cfg_type":1,"requestid":1171569,"platform":0}

**Comment by RedShameA** [comment]
那个E不会是自动生成的校验位吧😓

**Comment by hanfeihang** [comment]
如果你的运行环境有这个奇怪的现象的话，可以动手把第一个字符干掉吧。
