### ISSUE TITLE
新版本点击地图后旧方框不消失

### ISSUE THREAD

**Issue by PearXOrange** [hanfeihang/zhuoyao#22]
首先感谢作者为大家提供的游戏工具，提一个小建议，新版本更新后，点击地图出现方框及半透明背景，点击多次之后背景色会累加，导致无法看清地图，方框不消失，导致看起来很乱，最终只能刷新页面来继续。希望作者大大可以改进下，感谢~

**Comment by hanfeihang** [comment]
方框是用来标识这次扫面范围的。如果没方框提示，扫描稀有妖灵时都不知道这次扫面的范围多大。
大家需求不一样，欢迎根据自己的需求修改代码。

**Comment by PearXOrange** [comment]
嗯，其实倒不是方框提示有问题，而是多次点击出现多个方框叠加再加上背景色叠加就会很乱。我自己修改了下背景色的透明度和边框的透明度，现在好受多了哈哈。还有那个大范围搜索感觉不是很实用，其实可以以当前位置为起点旋转获取会更好？还有保存点的json第三个属性是time，感觉可以换成自定义提示之类的，然后点击这个按钮后可以定位过去，不然不能看位置直接飞行很容易位移过大被封号
