### ISSUE TITLE
npm start 一直卡住。。。我要vpn吗

### ISSUE THREAD

**Issue by rachelandxiaoleilei** [hanfeihang/zhuoyao#23]

**Comment by rachelandxiaoleilei** [comment]
zhangleideMacBook:zhuoyao-master zhanglei$ npm audit fix
+ body-parser@1.19.0
+ express@4.17.1
added 4 packages from 4 contributors, removed 6 packages and updated 16 packages in 6.597s
fixed 3 of 7 vulnerabilities in 193 scanned packages
  4 vulnerabilities required manual review and could not be updated
zhangleideMacBook:zhuoyao-master zhanglei$ npm start

> node-demo@0.0.0 start /Users/zhanglei/Downloads/zhuoyao-master
> node ./bin/www

**Comment by hanfeihang** [comment]
不需要vpn
