### ISSUE TITLE
腾讯好想更新接口了，而且妖灵库也更新了，现在的版本好想websocket经常断，扫不到妖

### ISSUE THREAD

**Issue by Anry** [hanfeihang/zhuoyao#26]

**Comment by hanfeihang** [comment]
妖灵库更新了，接口失效问题很难办。需要有安卓反编译大佬看看小程序现在改成什么样子了。

**Comment by Anry** [comment]
> 妖灵库更新了，接口失效问题很难办。需要有安卓反编译大佬看看小程序现在改成什么样子了。

我看这个项目地图雷达：https://github.com/liuzirui1122/zhuoyao_radar/
里面提到了接口有更新， 他更新了代码

**Comment by hanfeihang** [comment]
一段时间没管，这个腾讯的接口好像又能用了
