### ISSUE TITLE
问一下ios_GPS.JS能否单独加到其他雷达使用？

### ISSUE THREAD

**Issue by yqchen14** [hanfeihang/zhuoyao#4]
原作者的雷达上做了一些改动，增大了范围并增加了时间显示，我是不是只要把ios_gps这个js引入到那个雷达上，就可以点击自动生成GXP文件并自动启用了？

**Comment by hanfeihang** [comment]
我已经把雷达页面，改造成了nodejs服务，才支持了定位的功能。光迁移一个ios_gps.js文件，是没有用的。
我觉得把原作者的页面移到本项目，工作量更小，建议你试试。欢迎PR
