### ISSUE TITLE
大神能加个QQ吗,请教个

### ISSUE THREAD

**Issue by su350380433** [hanfeihang/zhuoyao#5]
QQ：350380433

一直报
GET / 304 0.365 ms - -
GET / 304 0.398 ms - -

地图上也没显示妖灵哈。

**Comment by su350380433** [comment]
使用osacomplie指令对apple_script文件夹内的脚本进行编译，并产出可执行脚本。将文件路径保存到iOS_gps.js文件内的变量apple_script_position

这步是什么意思呢，怎么执行啊。
是在哪个文件夹执行呢？

**Comment by hanfeihang** [comment]
兄弟，学一下AppleScript
