### ISSUE TITLE
报错是要怎么处理啊

### ISSUE THREAD

**Issue by su350380433** [hanfeihang/zhuoyao#7]
error "“System Events”遇到一个错误：不能获得“menu item \"Location\" of menu 1 of menu item \"Simulate Location\" of menu 1 of menu bar item \"Debug\" of menu bar 1 of process \"Xcode\"”。" number -1728 from menu item "Location" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode"

![image](https://user-images.githubusercontent.com/7920527/57762096-669a4580-7731-11e9-80a8-962059a42c38.png)

**Comment by hanfeihang** [comment]
不回答此类调试问题

**Comment by MikeyKapro** [comment]
查看系统偏好设置-安全与隐私-辅助功能-隐私的脚本编辑器是否勾选
